apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
        - name: go
          image: kuriansijo/hello-world:<VERSION>
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: go
  name: hello-world-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go
  type: LoadBalancer
